version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
  build-project:
    jobs:
      build:
        machine:
          image: ubuntu-2004:202010-01
        steps:
          - run:
             name: "building"
             command: npm run build

