version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    steps:
      - checkout
      - run: npm run build
  test:
    steps:
      - checkout
      - run: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test
